# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
s3access: &s3access
  s3_bucket:              <%=ENV["S3_BUCKET"]%>
  aws_access_key_id:      <%=ENV["AWS_ACCESS_KEY_ID"]%>
  aws_secret_access_key:  <%=ENV["AWS_SECRET_ACCESS_KEY"]%>

development:
  secret_key_base: 1ae64c366554f5e9826e4e1716b64009dd2f5677a97d22a4f6315c42d0727eee127a2c99929c6269cec6624469691ed19872332d5321d17fb3730f37ed67ed77

test:
  secret_key_base: 90782f2db86ee3260d8c522d58d2dfee47cd91c6eaa67276f551f1610d06f438428d8c855e3bf6e148736b24dfaed5ffa423aa6e7004600ac2d9a5bb57993b1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  <<: *s3access
